### ISSUE TITLE
Backend Files are not setup as shown in tutorials

### ISSUE THREAD

**Issue by sethtodd76** [nevarok/NevarokML#6]
In the tutorials, it shows going through the editor preferences to the source folder to unpack the back-end files. When someone downloads the repo from GitHub, the source folder does not look the same as it does in the tutorial. There is no executable folder to unpack like you do in the video. There is a "NevarokML" folder, "NevarokMLEditor" folder, "NevarokMLNodes" folder, and 3 "NevarokMLExe.zip" files.... labeled 001, 002, 003. Because of this, the unpacking backend step does not work and neither do any of the maps. Could you please help with this?
![Screenshot 2024-02-21 175453](https://github.com/nevarok/NevarokML/assets/157400389/c6f1c2f3-dbac-4532-860e-b52adf21827c)

**Comment by nevarok** [comment]
Hello @sethtodd76,

[GitHub NevarokML Reinforcement Learning Plugin Installation in Unreal Engine](https://youtu.be/nFbgVGCifA8)

This tutorial offers detailed instructions on how to install NevarokML from GitHub.

Please feel free to reach out if you have any further questions or need additional assistance. Your feedback and inquiries are always welcome.

**Comment by sethtodd76** [comment]
Hello Nevarok, I watched and followed closely with that tutorial BEFORE asking for help. The problem did not lie in my setup procedure. The problem is, as I said in my original post, in the source folder on your repo... "There is no executable folder to unpack like you do in the video. There is a "NevarokML" folder, "NevarokMLEditor" folder, "NevarokMLNodes" folder, and 3 "NevarokMLExe.zip" files.... labeled 001, 002, 003." 

You can even try downloading your own folder and seeing if there an NevarokML EXE file in it, and there is not.

**Comment by nevarok** [comment]
Hi @sethtodd76 ,

At [1:48](https://youtu.be/nFbgVGCifA8?t=108) of the video, you can find instructions on how to extract the executable folder.

The archive has to be extracted in the same way as shown at [1:48](https://youtu.be/nFbgVGCifA8?t=108) to receive the correct setup.

Please also check the [discussion](https://github.com/nevarok/NevarokML/discussions/5) to see if it helps to resolve your problem.

Feel free to reach out if you have any further questions or need additional assistance. Your feedback and inquiries are always welcome.

**Comment by nevarok** [comment]
Hi @sethtodd76 ,

My pleasure.

In case you have any other questions or facing some related issues please let me know.

Have fun!
