### ISSUE TITLE
Support for Engine 5.4 and FAB?

### ISSUE THREAD

**Issue by DanTulovsky** [nevarok/NevarokML#8]
Hi!

I would love to try and use this, but it doesn't seem to work with UE 5.4:

<img width="280" alt="image" src="https://github.com/user-attachments/assets/74d528e6-b79e-4002-aa11-8f25c2c4ca7c">

It also isn't available in FAB, so the above is just me putting it into the plugins folder.

Any chance you can update this to work with 5.4 (and 5.5)?

Thank you!

**Comment by nevarok** [comment]
Hello @DanTulovsky ,

I will update it as soon as I can find some time. Unfortunately, I'm currently juggling multiple projects, which has delayed my progress. Thank you for your patience.

Best regards,
