### ISSUE TITLE
Mac support?

### ISSUE THREAD

**Issue by DanTulovsky** [nevarok/NevarokML#9]
Hi,

Is it possible for this to support Mac?  Trying to use it:

```
Creating makefile for NevarokML0Editor (no existing makefile)
Platform Mac is not a valid platform to build. Check that the SDK is installed properly.
```

thank you

**Comment by nevarok** [comment]
Hello @DanTulovsky ,

Unfortunately, due to the complexity of the project, I am unable to offer support for macOS at this time. I appreciate your understanding.

Best regards,
